# Generated by Django 2.0.2 on 2018-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarentry',
            name='datetime',
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
