# Generated by Django 2.0.2 on 2018-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20180212_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarentry',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='calendarentry',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='date',
            field=models.DateField(default='2018-12-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
